[project]
name = "debugging-deep-dive"
version = "0.1.0"
requires-python = ">=3.9.0"
dependencies = [
    "flask>=3.1.2",
    "jupyter>=1.1.1",
    "remote-pdb>=2.1.0",
]

[tool.uv.workspace]
members = [
    "03-pdbpp",
]
